spring:
  application:
    name: workflow-service

  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

  cloud:
    config:
      fail-fast: true

logging:
  level:
    root: INFO
    com.sirp.workflow: DEBUG

loki:
  push-url: ${LOKI_PUSH_URL:http://localhost:3100/loki/api/v1/push}

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework
