server:
  port: 8888

spring:

  application:
    name: config-server

  profiles:
    active: native

  cloud:

    config:

      server:

        native:

          search-locations:

            classpath:/config

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus